# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
target 'myproject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myproject

  target 'myproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myproject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myproject-tvOS

end
